name: ci-main

on:
  push:
    branches:
    - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities on IaC
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --dev --all-projects 
                --severity-threshold=critical --severity-threshold=high --severity-threshold=medium  --severity-threshold=low  --report 