name: ci-main

on:
  push:
    branches:
    - main

# inputs:
#   working_directory:
#     description: 'The directory to run the Snyk command in'
#     required: false
#     default: ./etc/ ./components/ ./modules/


env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  working_directory: ./etc/ ./components/ ./modules/

jobs:
  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ${{ env.working_directory }}
          args: --severity-threshold=critical --severity-threshold=high --severity-threshold=medium  --severity-threshold=low  --report 