name: ci-main

on:
  push:
    branches:
    - main

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snykScan:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk iac test etc/ components/ modules/ --severity-threshold=critical --severity-threshold=high --severity-threshold=Medium         
            #  snyk iac test etc/ components/ modules/ --severity-threshold=high 

      - name: run Snyk Code Test
        run: snyk code test
