name: ci-main

on:
  push:
    branches:
    - main


jobs: 
  snykScan:
    name: Snyk Scan
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk test
        run: snyk iac test etc/ components/ modules/ --severity-threshold=medium 
             snyk iac test etc/ components/ modules/ --severity-threshold=high 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  # terraform_plan:
  # name: build
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
      
  #   - uses: pre-commit/action@v3.0.0
  #     with: 
  #       extra_args: terraform_fmt --all-files
        
  #   - uses: stefanzweifel/git-auto-commit-action@v4
  #     with:
  #       file_pattern: etc/* components/* modules/*
  

# generate_relese:
#   name: create_release
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: Release ${{ github.ref }}
#         body: |
#           Changes in this Release
#           - First Change
#           - Second Change
#         draft: false
#         prerelease: false