name: "deploy"

on:
  workflow_dispatch:
    inputs:
      severity:
        type: string
        description: 'The severity of the vulnerability to report'
        required: true
  
     
jobs:
  dev:
    uses: NickAzureDevops/pre-commit-hooks/.github/workflows/iac_security_run.yml@test-snyk
    with: 
      working_directory: ${{ inputs.working_directory}}
      severity: ${{ inputs.severity}}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  