name: "deploy_dev"
on:
  workflow_dispatch:
      
jobs:
  snyk:
    uses: NickAzureDevops/pre-commit-hooks/.github/workflows/iac_security_run.yml@test-snyk
    with: 
      working_directory: ${{ inputs.working_directory}}
      severity: ${{ inputs.severity}}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  