name: "deploy"

on:
  workflow_dispatch:
    inputs:
      severity:
        type: string
        description: 'The severity of the vulnerability to report'
        required: false
      working_directory:
        type: string
        description: 'The directory to run the Snyk command in'
        required: false
        default: ./etc/ ./components/ ./modules/  ./bootstrap/
      
jobs:
  snyk:
    uses: NickAzureDevops/pre-commit-hooks/.github/workflows/iac_security_run.yml@test-snyk
    with: 
      working_directory: ${{ inputs.working_directory}}
      severity: ${{ inputs.severity}}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  